In [1]:
# importing the packages
import pandas as pd
import numpy as np

In [2]:
# reading the csv files
orders = pd.read_csv('orders_test (2).csv')
stores = pd.read_csv('store_test (2).csv')
customers = pd.read_csv('customer_test (2).csv')

1. Create a CSV containing an aggregate table showing the total orders and revenue
each store had each month. It should have the following columns:

Year (Eg: 2020)

Month (Eg: January)

Store Name

Number of Orders

Total Revenue

In [3]:
# renaming, creating, merging columns as per required output
stores.rename(columns={'id':'store_id'},inplace=True)
orders['order_date'] = pd.to_datetime(orders['order_date'])
orders['Year'] = orders['order_date'].apply(lambda x : x.strftime('%Y'))
orders['Month'] = orders['order_date'].apply(lambda x : x.strftime('%B'))
store_orders = stores.merge(orders, on=['store_id'], how = 'left')

In [4]:
store_orders.groupby(['name','Year','Month']).agg({'id':'count','total':'sum'}).reset_index().rename(columns={
                    'name':'Store Name','id':'Number of Orders','total':'Total revenue'})

                   Store Name  Year     Month  Number of Orders  Total revenue
0   Adams, Barrett and Thomas  2020     April                27         354.82
1   Adams, Barrett and Thomas  2020  February                24         436.31
2   Adams, Barrett and Thomas  2020   January                27         315.79
3   Adams, Barrett and Thomas  2020     March                27         430.58
4   Adams, Barrett and Thomas  2020       May                 4          90.45
5            Edwards-Mcdaniel  2020     April                30         416.12
6            Edwards-Mcdaniel  2020  February                22         439.02
7            Edwards-Mcdaniel  2020   January                18         280.72
8            Edwards-Mcdaniel  2020     March                29         428.32
9            Edwards-Mcdaniel  2020       May                 1          24.43
10                   Hall Inc  2020     April                25         391.25
11                   Hall Inc  2020  February                22         381.18
12                   Hall Inc  2020   January                21         348.17
13                   Hall Inc  2020     March                19         286.01
14                   Hall Inc  2020       May                 2          44.05
15  Henderson, Olson and Ward  2020     April                24         319.29
16  Henderson, Olson and Ward  2020  February                25         342.60
17  Henderson, Olson and Ward  2020   January                23         282.65
18  Henderson, Olson and Ward  2020     March                23         312.72
19  Henderson, Olson and Ward  2020       May                 3          60.27
20  Martinez, Marsh and Gomez  2020     April                23         361.04
21  Martinez, Marsh and Gomez  2020  February                33         442.74
22  Martinez, Marsh and Gomez  2020   January                17         222.38
23  Martinez, Marsh and Gomez  2020     March                36         573.24
24  Martinez, Marsh and Gomez  2020       May                 1          19.53
25                Scott-Brown  2020     April                20         391.18
26                Scott-Brown  2020  February                19         274.21
27                Scott-Brown  2020   January                18         216.82
28                Scott-Brown  2020     March                13         197.24
29                Scott-Brown  2020       May                 3          14.17
30               Stevens-Barr  2020     April                24         343.31
31               Stevens-Barr  2020  February                24         322.05
32               Stevens-Barr  2020   January                27         455.03
33               Stevens-Barr  2020     March                31         488.47
34               Stevens-Barr  2020       May                 1          24.61
35                 Taylor Ltd  2020     April                24         393.15
36                 Taylor Ltd  2020  February                27         343.66
37                 Taylor Ltd  2020   January                28         450.72
38                 Taylor Ltd  2020     March                26         428.81
39                 Taylor Ltd  2020       May                 5          83.29
40                 Valdez Inc  2020     April                26         406.61
41                 Valdez Inc  2020  February                25         383.29
42                 Valdez Inc  2020   January                24         357.64
43                 Valdez Inc  2020     March                29         463.58
44                 Valdez Inc  2020       May                 2          39.25
45                Young Group  2020     April                26         366.12
46                Young Group  2020  February                26         404.18
47                Young Group  2020   January                15         271.67
48                Young Group  2020     March                23         356.60
49                Young Group  2020       May                 8         114.65

In [5]:
# storing the csv for question 1 reesults
Q1 = store_orders.groupby(['name','Year','Month']).agg({'id':'count','total':'sum'}).reset_index().rename(columns={
                    'name':'Store Name','id':'Number of Orders','total':'Total revenue'})
Q1.to_csv('Q1.csv')

2. Create a CSV containing a list of users who have placed less than 10 orders. It should have the following columns:

First Name

Last Name

Email

Orders Placed by user

In [6]:
# renaming, merging columns as per required output
customers.rename(columns={'id':'customer_id'},inplace=True)
customer_orders = customers.merge(orders,on='customer_id',how='left')
customers_with_orders = customer_orders.groupby(['first_name','last_name','email']).agg({'id':'count'}).reset_index().rename(
    columns={'first_name':'First Name','last_name':'Last Name','email':'Email','id':'Orders Placed by user'})

In [7]:
# pulling customer info who has ordered less than 10 orders
customers_with_lt_10_orders = customers_with_orders[customers_with_orders['Orders Placed by user'] < 10]

In [8]:
customers_with_lt_10_orders

,First Name,Last Name,Email,Orders Placed by user
0,Alexandria,Alvarado,sjohnston@young-brewer.biz,4
2,Alicia,Martinez,jenniferestrada@yahoo.com,6
3,Angela,Oneal,nataliewarner@hotmail.com,7
4,Angela,Taylor,staffordkimberly@gmail.com,9
5,Beverly,Barnes,mitchellkyle@yahoo.com,5
7,Brian,Riley,lauren30@gmail.com,8
8,Brooke,Brown,melissacoleman@hotmail.com,9
12,Charles,Randall,ihall@gmail.com,7
17,Dale,Sanders,ohernandez@hart.com,7
18,David,Collins,terri55@cooper-turner.com,8
19,Dennis,Knapp,hayesphillip@harris-klein.com,9
25,Francis,Smith,jasonsmith@smith.com,9
28,Heather,Dennis,melissa24@rodriguez-carey.biz,9
29,Hector,Hayden,beth39@richardson-williams.com,9
30,James,Washington,ashleysnow@gmail.com,8
31,Jamie,Shah,jacobchavez@gmail.com,9
32,Jason,Moore,lisa30@russell-francis.com,7
34,Jennifer,Collins,kimberlycole@adams.net,9
35,Jennifer,Jones,eowens@scott.com,6
36,Jeremy,Shaw,charlesfleming@yahoo.com,7
37,Joanna,Terry,aprilwilliams@yahoo.com,7
39,Johnny,Campbell,tracywells@brown.com,8
44,Katherine,Johnson,ericgilbert@gmail.com,8
46,Kayla,West,hallbrenda@klein.biz,8
49,Latoya,Smith,ronaldbaker@adams.com,9
52,Lee,Williams,johnwilliams@gmail.com,7
53,Linda,Kelley,jason51@gmail.com,9
54,Lisa,Mckay,nicolas18@herrera.com,6
55,Lisa,Olsen,sbarnes@george-sullivan.com,7
56,Manuel,Anderson,saramorse@gmail.com,6
61,Melissa,Cooke,mstephenson@gmail.com,6
62,Melvin,Stone,pamelamyers@newman.info,5
63,Meredith,French,farrelllawrence@yahoo.com,9
65,Michelle,Bridges,carlsonanthony@peck.net,7
68,Nichole,Morris,samanthamoore@archer.com,7
70,Olivia,Hudson,estevens@wells.net,8
72,Paul,Smith,martinezjessica@porter.com,8
74,Regina,Barber,qjackson@hill-ball.org,6
77,Richard,Peterson,nancy53@hotmail.com,8
81,Ryan,Le,joneskelly@alvarado.com,8
82,Ryan,Robinson,joyashley@scott.com,6
83,Ryan,Terrell,carsondaniel@yahoo.com,6
84,Sara,Ramirez,samantha67@yahoo.com,9
85,Shelby,Osborn,angelanelson@yahoo.com,5
87,Steven,Richard,howard63@gonzalez.info,7
88,Tanya,Holmes,hlucas@boyer.com,6
90,Thomas,Montgomery,abigailfrost@gillespie-francis.com,8
92,Travis,Barnes,tracigaines@gmail.com,7
93,Travis,Phelps,andrew38@yahoo.com,7

In [9]:
# saving the results of Q2
customers_with_lt_10_orders.to_csv('Q2.csv')

3. In question 2, use a MD5 hash to encrypt the emails of the users before converting it to CSV.

In [10]:
# importing the hash library
import hashlib

In [11]:
# hasing the Email information of customer
customers_with_lt_10_orders['Email']=customers_with_lt_10_orders.Email.apply(lambda x: hashlib.md5(x.encode()).hexdigest())

In [13]:
customers_with_lt_10_orders

,First Name,Last Name,Email,Orders Placed by user
0,Alexandria,Alvarado,6c5e7059be20c0fc930df3624e16f9a7,4
2,Alicia,Martinez,73d4e1335c8b73f4498e6626791ae013,6
3,Angela,Oneal,f2137375b2faa52d3c598b0963187c9a,7
4,Angela,Taylor,10b39830a7ba957429d57e89ad7a4feb,9
5,Beverly,Barnes,79a0ea032f92e7993ea7431f2a582b5e,5
7,Brian,Riley,32c074fa19009a10e6a906b960151c4b,8
8,Brooke,Brown,56d085f32f17825b3f70c4529803a7ed,9
12,Charles,Randall,7648732290f1d67c958bad1dff4f46d5,7
17,Dale,Sanders,f4dbaf5d6abecd487f82334edec609b1,7
18,David,Collins,050ec448b62eb2f80f05d84e477fa1d8,8
19,Dennis,Knapp,ca529c3ef1f75771b2cf6e1daebe53e3,9
25,Francis,Smith,1ba4b9f41b984914a39f915800427e37,9
28,Heather,Dennis,7a1dc931bb736ddcac1426bd7de5db51,9
29,Hector,Hayden,edd568df453b10c43d9406864047d088,9
30,James,Washington,71a32f6bd1ba1407a89a7d42323391a0,8
31,Jamie,Shah,a7adaec26ca18e56b58f1d3bcf356997,9
32,Jason,Moore,b5075cf22f983d637daaeaea3fd281c4,7
34,Jennifer,Collins,6c98acd6b8b7d82b2dda93358f7b7d66,9
35,Jennifer,Jones,d0bf0e4ec96c6f3ba89c8b3061d43afa,6
36,Jeremy,Shaw,2f40dfd43fa285d19c7262d31e008c81,7
37,Joanna,Terry,f9477c84df3fa1addf8fb94a5bd41b6c,7
39,Johnny,Campbell,0cc70fe75f583592ebd844bf22660859,8
44,Katherine,Johnson,b4ea219b3ca7e51251a24b4226b05d1d,8
46,Kayla,West,a201a2f75986c62a6a7861c568c01afe,8
49,Latoya,Smith,a928d28dcb1cb225eece9759355b7bf5,9
52,Lee,Williams,6e88dc3000d1130acf038bfae39e8116,7
53,Linda,Kelley,7c6d9cfe9505ce2304207cf96ebe15cc,9
54,Lisa,Mckay,c146b7fba37684f0b397280f9c717687,6
55,Lisa,Olsen,4a994706a21b707f115bbbec09eefb05,7
56,Manuel,Anderson,6e66f2f4bff15fa9719fb34bc10dbdf3,6
61,Melissa,Cooke,5bce1b9e424cf4f54946e4a705d27f74,6
62,Melvin,Stone,e6deb931b67402a69947e84a7f92de29,5
63,Meredith,French,98184d7fe4f3610f628d7e98fa7af09d,9
65,Michelle,Bridges,80badfc300534d4506fb7404263981a1,7
68,Nichole,Morris,585265c94b51e011901e46c0c348ad45,7
70,Olivia,Hudson,335444f3cbb088d2ed90ef32bd456555,8
72,Paul,Smith,03fab0b43d2e3b7f59b991b5cc0d47c6,8
74,Regina,Barber,8eb7b87ac1f3fc59e067a0d1162aab43,6
77,Richard,Peterson,c637e9b68f817c6e2282aa124846a6ae,8
81,Ryan,Le,ce4959a23975d2833727c49b63bcbc7c,8
82,Ryan,Robinson,e1d7f957f110ac7b8a2d564096cf9a49,6
83,Ryan,Terrell,f7b1672d53d0ae4b07021aea9cf9f143,6
84,Sara,Ramirez,84d79088d5b6c337797b414f0a537413,9
85,Shelby,Osborn,8503336e0f3a2be920984c4f9c6db980,5
87,Steven,Richard,77fcee2714d485a53c410c43d5010dec,7
88,Tanya,Holmes,974007ae906d87dc269cf273e6c67e01,6
90,Thomas,Montgomery,2a011e8e05b91ce7c5fda8fb679506f1,8
92,Travis,Barnes,bc20d5b5cbf6d2a76dd4b2624a76b2e8,7
93,Travis,Phelps,a750ecf95c82cc5ff2d2124339ed8884,7

In [14]:
# stroing the customer order info with hashed Email information 
customers_with_lt_10_orders.to_csv('Q3.csv')